### ISSUE TITLE
Error when using yarn to install dependencies

### ISSUE THREAD

**Issue by actanasoiu** [mike-works/vscode-fundamentals#26]
When I'm trying to install dependencies using the command "yarn", I get this message:

_error An unexpected error occurred: "npm/@types%2fkoa-static: Invalid URI \"npm/@types%2fkoa-static\""._

Sample from the "yarn-error.log" :

Arguments: 
  /Users/atanasoi/.nvm/versions/node/v8.9.1/bin/node /Users/atanasoi/.nvm/versions/node/v8.9.1/bin/yarn

PATH: 
  /Users/atanasoi/.nvm/versions/node/v8.9.1/bin:/usr/local/opt/openssl/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/openssl/bin

Yarn version: 
  1.3.2

Node version: 
  8.9.1

Platform: 
  darwin x64

  koa-static@^4.0.1:
    version "4.0.1"
    resolved "https://registry.yarnpkg.com/koa-static/-/koa-static-4.0.1.tgz#b99521ed848d7adb79acae9c824d8d8277a8c4d5"
    dependencies:
      debug "^2.6.8"
      koa-send "^4.1.0"
  

Trace: 
  Error: npm/@types%2fkoa-static: Invalid URI "npm/@types%2fkoa-static"
      at Request.module.exports.Request.init (/Users/atanasoi/.nvm/versions/node/v8.9.1/lib/node_modules/yarn/lib/cli.js:123173:31)
      at new Request (/Users/atanasoi/.nvm/versions/node/v8.9.1/lib/node_modules/yarn/lib/cli.js:123027:8)
      at request (/Users/atanasoi/.nvm/versions/node/v8.9.1/lib/node_modules/yarn/lib/cli.js:121625:10)
      at RequestManager.execute (/Users/atanasoi/.nvm/versions/node/v8.9.1/lib/node_modules/yarn/lib/cli.js:62141:17)
      at RequestManager.shiftQueue (/Users/atanasoi/.nvm/versions/node/v8.9.1/lib/node_modules/yarn/lib/cli.js:62168:10)
      at promise.default (/Users/atanasoi/.nvm/versions/node/v8.9.1/lib/node_modules/yarn/lib/cli.js:61947:12)
      at new Promise (<anonymous>)
      at new F (/Users/atanasoi/.nvm/versions/node/v8.9.1/lib/node_modules/yarn/lib/cli.js:29389:28)
      at RequestManager.request (/Users/atanasoi/.nvm/versions/node/v8.9.1/lib/node_modules/yarn/lib/cli.js:61945:21)
      at NpmRegistry.request (/Users/atanasoi/.nvm/versions/node/v8.9.1/lib/node_modules/yarn/lib/cli.js:30362:32)

**Comment by mike-north** [comment]
Interesting. Have you tried using NPM instead of yarn?

**Comment by actanasoiu** [comment]
It works with NPM. Didn't occur to me to try NPM as well. 
Just thought that there's something wrong with the package "koa-static" and both yarn and npm are  loading it from the same path.
Please close the issue if that's alright with you.
